apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: docker.io/waveywaves/mirrord-queues-debug-ex-consumer:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-0.kafka.default.svc.cluster.local:9092"
        command: ["python"]
        args: ["kafka_consumer.py"] 