apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      auto.create.topics.enable: "true"
      delete.topic.enable: "true"
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafbat
  template:
    metadata:
      labels:
        app: kafbat
    spec:
      containers:
        - name: kafbat
          image: ghcr.io/kafbat/kafka-ui:latest
          ports:
            - name: http-port
              containerPort: 8090
              protocol: TCP
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: kafka
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-kafka-bootstrap.default.svc:9092"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: SERVER_PORT
              value: "8090"
