apiVersion: queues.mirrord.metalbear.co/v1alpha
kind: MirrordKafkaTopicsConsumer
metadata:
  name: kafka-consumer-topics
  namespace: default
spec:
  consumerApiVersion: apps/v1
  consumerKind: Deployment
  consumerName: kafka-consumer
  topics:
  - id: test_topic
    clientConfig: base-config
    nameSources:
    - directEnvVar:
        container: consumer
        variable: KAFKA_TOPIC
    groupIdSources:
    - directEnvVar:
        container: consumer
        variable: KAFKA_GROUP_ID 